### ISSUE TITLE
Suggestions for controls

### ISSUE THREAD

**Issue by zefexdeveloper** [lucaspulliese/vue-cool-lightbox#10]
1. Add tooltip for the buttons. You can use [<title>](https://developer.mozilla.org/pt-BR/docs/Web/SVG/Element/title) inside the SVG - it's not very accessible without it. The problem with using encapsulated title is that sometimes people want to make it another language so it's probably good to have a prop or a slot for that.
![image](https://user-images.githubusercontent.com/30276092/74985419-2c737800-5416-11ea-9b27-718396612c04.png)

2. Add possibility to disable the gallery. I don't think that all users will want that, sometimes we just want a simple lightbox
![image](https://user-images.githubusercontent.com/30276092/74985507-5a58bc80-5416-11ea-9f5c-554dbd9a1ccf.png)

**Comment by lucaspulliese** [comment]
Hi @zefexdeveloper!

1. Great, my idea was to add this enhancement in the new version, I just have to think what is the best way to have organized the language file and their props.

2. Yep, I will add it too.

Thanks!

**Comment by zefexdeveloper** [comment]
@lucaspulliese Looking forward to it. I'm actually thinking on using it for a website I'm creating now for a client but I kinda need those features first, specially the second one.

Thank you very much hermano.

**Comment by lucaspulliese** [comment]
I can have the second one for today. This weekend I'm going on vacations so I guess for the next week maybe for the accessibility enhancement.

**Comment by lucaspulliese** [comment]
Added "gallery" prop in [1.0.13](https://www.npmjs.com/package/vue-cool-lightbox), wich enable/disable gallery button and gallery block 👍

**Comment by zefexdeveloper** [comment]
Thank you very much, I will be using it.

**Comment by zefexdeveloper** [comment]
Thank you
