### ISSUE TITLE
Add drag and I love it.

### ISSUE THREAD

**Issue by isuke01** [lucaspulliese/vue-cool-lightbox#11]
Actually I think drag/swipe is really feature that is missing. 
Other than that I really like it, but it cant be used if there is no swipe for mobile devices :/

**Comment by lucaspulliese** [comment]
Hi @isuke01! 

Well, you have arrows to change the slides 😅

But yes, I think that's is gonna be an awesome feature. This weekend I'm on vacations but I'll try to have it for the next week. I don't know how much time it gonna takes me.

Thanks @isuke01!

**Comment by zefexdeveloper** [comment]
+1 for this feature

**Comment by lucaspulliese** [comment]
Added swipe slides on mobile, the lightbox still has the fade effect when the slide change, but now you can change those slides swipping them. 

I would like to add in the future the drag and swipe effect just like [fancybox](https://fancyapps.com/fancybox/3/) does.

**Comment by isuke01** [comment]
WOW!
Thanks for effort!
I still think drag would be nice on desktop too. You may laugh but I started to use carousels, etc with drag feature on desktop since I discovered, my parents actually are using drag swipe on touch screens (MS surface) and they are love it:D

**Comment by lucaspulliese** [comment]
You are welcome!

You have a good point there, I guess I'm going to accelerate the release 2.0, which I will add the drag swipe effect on mobile devices and desktop too.

Thanks for your feedback, I really appreciate it.

**Comment by zefexdeveloper** [comment]
@lucaspulliese I'm here just to say that you are doing a really great job, thank you for all the effort. Gracias hermano.

**Comment by lucaspulliese** [comment]
You're welcome hermano!

And I really really appreciate your words, thank you very much!

**Comment by lucaspulliese** [comment]
Finally I finished V2, you can check the swipe effect and tell me how do you see it, If you think everything is fine please let me know :D

https://vue-cool-lightbox.lucaspulliese.com/
