### ISSUE TITLE
Allow to change the color on the gallery

### ISSUE THREAD

**Issue by zefexdeveloper** [lucaspulliese/vue-cool-lightbox#12]
Right now I think that the color is hard coded as red, it would be nice to allow changing it like the progress indicator and as default match the color of the progress indicator, like if the user doesn't specify the color for the gallery it will match the progress color, this way the user can just change the progress color and it will reflect on the gallery, or if the wants to change the progress to one color and the gallery to another he just have to set both.

**Comment by lucaspulliese** [comment]
Looking at the issue #15, what do you think is the best or proper way to handle this? Using props or extract the CSS file and allow developers to change those colors via CSS?

**Comment by zefexdeveloper** [comment]
Having the CSS extracted allows you to simplify your props, meaning that they will handle stuff related to the component itself and not styling, it's more like a separation of responsibility. In cases where it's a simple component, having props to set classes and stuff such as colors are just fine but in your case where it's kinda complex, it can't be all tied up to one style.

+1 for extracting the CSS file and allow people to import it separated and create themes.

**Comment by lucaspulliese** [comment]
Great! Thanks for your explanation!
