### ISSUE TITLE
Change the slidershow control icon

### ISSUE THREAD

**Issue by zefexdeveloper** [lucaspulliese/vue-cool-lightbox#14]
I noticed that when pressing pause on the slidershow it does actually resets meaning it's not actually a pause button but a stop one, perhaps you should change the icon or implement an actual pause for the slidershow.

Thank you

**Comment by lucaspulliese** [comment]
Changed in V2, and added swipe effect! 

https://vue-cool-lightbox.lucaspulliese.com/
