### ISSUE TITLE
Extract component CSS to a file

### ISSUE THREAD

**Issue by zefexdeveloper** [lucaspulliese/vue-cool-lightbox#15]
Having the CSS contained inside the component is bad cause it won't allow people to make changes without using the `!important` which is really bad. I recommend creating an external CSS file for theming, this way people can customize their own and include like `import 'theme.css'`.

**Comment by lucaspulliese** [comment]
Yep, you are correct with this one. Thanks!

**Comment by lucaspulliese** [comment]
Added in the new version 1.1.0 :D 

`
import 'vue-cool-lightbox/dist/vue-cool-lightbox.min.css'
`
