### ISSUE TITLE
Mobile swiping feedback

### ISSUE THREAD

**Issue by pknijff** [lucaspulliese/vue-cool-lightbox#16]
Hi,
First some credits to this package, it comes really close to Fancybox in my opinion.
However, swiping on mobile isn't as user friendly as I hoped for.

For instance in Fancybox:
- Swiping up is closing the popup (now it scrolls the page behind)
- Swiping left or right leads to moving the image according to your movement, it feels snappy. (now it could scroll the page behind if not swiped perfectly horizontally)

Are there any plans for optimizing this behavior?

**Comment by lucaspulliese** [comment]
Hi @pknijff! 
Thank you very much, and thanks for your feedback.

Yes, the idea is to add these swipe optimizations and the accessibility optimizations for version 2 :)

**Comment by lucaspulliese** [comment]
Finally I finished V2, you can check the swipe effect and tell me how do you see it, If you think everything is fine please close the issue :D

https://vue-cool-lightbox.lucaspulliese.com/

**Comment by narindersahani** [comment]
Hi,
I want to place thumbnail section from right to bottom. Is there any option to do that ?

Thanks

**Comment by lucaspulliese** [comment]
Hi @narindersahani !

No, I will work on it 👍

**Comment by narindersahani** [comment]
Thanks for reply. 
Any custom code to display thumbnail section from right to bottom please

**Comment by lucaspulliese** [comment]
@narindersahani do you have an example or a screenshot of the design that you want to do?

**Comment by narindersahani** [comment]
Yes I have design for that here you go
![Screenshot (98)](https://user-images.githubusercontent.com/5082825/78419541-7af67200-7664-11ea-9d51-839d8f31d8ac.png)

**Comment by lucaspulliese** [comment]
Added thumbsPosition prop in version 2.1.0. [Check API documentation](https://vue-cool-lightbox.lucaspulliese.com/#props)

In your case you should set thumbsPosition to 'bottom'

**Comment by pknijff** [comment]
I checked it and it is working way better, well done! I'll use the lib definitely in future projects!
