### ISSUE TITLE
Cannot read property 'match' of undefined"

### ISSUE THREAD

**Issue by 19Danie93** [lucaspulliese/vue-cool-lightbox#18]
a have a error on charge the library, please help me
![image](https://user-images.githubusercontent.com/31352743/77052113-b3c6f380-69a2-11ea-9be1-c4c2588baf3f.png)

**Comment by lucaspulliese** [comment]
Hi @19Danie93!

Could you provide me the array of items wich are you using?

**Comment by 19Danie93** [comment]
this is my code in the component.
![image](https://user-images.githubusercontent.com/31352743/77095428-41770300-69e4-11ea-98cd-b4de7d9cd372.png)

**Comment by 19Danie93** [comment]
I already fixed it ... I realized that my file path was wrong.
Thank you very much for answering

**Comment by lucaspulliese** [comment]
No problem, thanks to you for using the component!
