### ISSUE TITLE
Trigger the gallery with just one image

### ISSUE THREAD

**Issue by fayazara** [lucaspulliese/vue-cool-lightbox#19]
Is it possible to show just 1 thumbnail and when it is opened, they gallery will have multiple items then.

Or even trigger it with a button, called "Open Gallery" and this opens tha gallery

**Comment by lucaspulliese** [comment]
Hi @fayazara.

You just need to set the index of the gallery, then the gallery will be opened, just like this codepen:

https://codepen.io/lucaspulliese/pen/LYVgyzp

**Comment by fayazara** [comment]
Thank you! This works
