### ISSUE TITLE
Lazy load full-res photos

### ISSUE THREAD

**Issue by wowselim** [lucaspulliese/vue-cool-lightbox#2]
Hey,
Is it currently possible to specify thumbnail URLs and full image URLs separately? I would like to display a grid with small thumbnails and lazy load the full images either when they are opened or I am likely to view it.
I have some large images and I don't want to unnecessarily load them in full resolution if a user never actually views them.

**Comment by lucaspulliese** [comment]
Hey!

Check the videos examples https://vue-cool-lightbox.lucaspulliese.com/#example-video.
There each item is an object like this:

```javascript
items: [
    {
       title: 'In nature, nothing is perfect and everything is perfect',
       description: "Photo by Lucas",
       thumb: 'https://scx1.b-cdn.net/csz/news/800/2019/1-nature.jpg',
       src: '/video.mp4',
    },
]
```

thumb is the thumbnail of the video and src is the url of the video, in your case src is the url of the full image.

Tell me if that is what you need.

**Comment by wowselim** [comment]
Hey, I must've missed that because I didn't really look at the video section. That's exactly it, thank you!
