### ISSUE TITLE
Cannot read property 'childNodes' of undefined

### ISSUE THREAD

**Issue by roberttolton** [lucaspulliese/vue-cool-lightbox#20]
Hey, I'm using this in a NuxtJS project, and am running into an error when using it inside of a component, one that can appear on the page many times.

I am importing the lightbox into each component.

The lightbox opens fine, but upon closing I get `Cannot read property 'childNodes' of undefined`:
```
item = this.$refs.items[this.imgIndex].childNodes[0];
```

Within the resetZoom method.

Any ideas?

**Comment by lucaspulliese** [comment]
Fixed in version 2.0.3
