### ISSUE TITLE
How to use with Nuxt ?

### ISSUE THREAD

**Issue by MattixNow** [lucaspulliese/vue-cool-lightbox#21]
I've saw the issue #8, but i don't works on my universal nuxt project. Can you help me ?

**Comment by lucaspulliese** [comment]
Hi @MattixNow!

Could you provide me the error?

**Comment by MattixNow** [comment]
No error, but the css file isn't loaded, I manually add it with a head tag inside my components

**Comment by MattixNow** [comment]
This happen only in production mode

**Comment by lucaspulliese** [comment]
Mm, that's weird. I will take a look today. 

Thanks.

**Comment by lucaspulliese** [comment]
I can't reproduce the error.

Could you post a screenshot of how you're using it?

**Comment by lucaspulliese** [comment]
Closed since no response, feel free to open the issue again if you want.

**Comment by danieldanielecki** [comment]
Same here, no success with Nuxt even after following #8

**Comment by leccyril** [comment]
now it is nuxtjs3 and it seems yout plugin is not compatible
