### ISSUE TITLE
Lazy loading

### ISSUE THREAD

**Issue by Webcretaire** [lucaspulliese/vue-cool-lightbox#24]
Hello

First of all, thanks a lot for this lightbox : it's easy to use and it has really nice features

I have a problem though, which is similar to #2 : I use the distinction between "src" and "thumb" attribute in my items, but when I click on an image, I can see in the network tab of my devtools that __all__ full-resolution image are downloaded immediately anyways (which is slow with dozens of images).

I checked that the correct images are displayed everywhere, i.e. in the thumbnail tabs the "thumb" image is displayed and the main image is the "src" one, which is the case

My code looks like this :
```vue
<template>
  <b-container fluid class="pl-5 pr-5">
    <cool-light-box
      :items="coolLightBoxItems"
      :index="index"
      @close="index = null"
      :fullScreen="true"
    />

    <b-row class="images-wrapper">
      <b-col
        cols="12"
        xl="4"
        lg="6"
        class="image-col mb-3"
        v-for="(image, imageIndex) in coolLightBoxItems"
        :key="imageIndex"
        @click="triggerLightbox(imageIndex)"
      >
        <b-img-lazy
          class="image"
          :src="image.thumb"
          :alt="image.description"
          :title="image.description"
          rounded
        />
      </b-col>
    </b-row>
  </b-container>
</template>

<script>
const CoolLightBox = () => import("vue-cool-lightbox");

export default {
  name: "Home",
  components: {
    CoolLightBox
  },
  data: () => ({
    photos: [
    {
        author: "First guy",
        description: "Cool photo",
        slug: "photo1"
    },
    {
        author: "Other dude",
        description: "Other photo",
        slug: "photo2"
    },
    {
        author: "First guy",
        description: "Guess what ? This is a photo",
        slug: "photo3"
    }],
    index: null
  }),
  computed: {
    coolLightBoxItems() {
      return this.photos.map(p => ({
        title: p.author,
        description: p.description,
        src: require(`@/assets/photos/${p.slug}.jpg`),
        thumb: require(`@/assets/photos/thumbnails/${p.slug}.jpg`)
      }));
    }
  },
  methods: {
    triggerLightbox(index) {
      this.index = index;
    }
  }
};
</script>
```

Is there any way to make the loading of full-size images truely lazy ? Did I miss an option somewhere ?

Thanks

**Comment by lucaspulliese** [comment]
Hi @Webcretaire! 

Thanks for your feedback!

This is a good enhancement to do, so I will be working on how to add it.

**Comment by Webcretaire** [comment]
Hi,

I just wanted to update you on the tests I did regarding this issue : my project uses [Bootstrap Vue](https://bootstrap-vue.js.org/), and if I replace all your `<img/>` tags with `<b-img-lazy/>` it seems to work as I expect (i.e. each image is downloaded only when it needs to be displayed).

It is not a good solution for this project because it would add a dependency on Bootstrap Vue (and maybe it broke some other feature that I don't use, I haven't tested it properly), but maybe it's possible to implement [something similar](https://bootstrap-vue.js.org/docs/components/image#lazy-loaded-images) using [Intersection Observer API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API)

**Comment by lucaspulliese** [comment]
Thanks! I was wondering how to do it, this gives me a point where I should start.

**Comment by Webcretaire** [comment]
No problem, I don't have much time for that (I only use it for a small personnal project, not my actual job), but if I can be of any help feel free to ask :slightly_smiling_face:

**Comment by lucaspulliese** [comment]
Hi @Webcretaire! 

Now in version 2.2.0 you have lazy loading on images! Thanks for the idea, I guess that the Intersection Observer API works very well. 

If it's working fine for you please close the issue.

**Comment by Webcretaire** [comment]
Hi !

It seems to be working really well, thanks a lot for this improvement ! Now that's a really cool vue-lightbox 🙂
