### ISSUE TITLE
Having issues with nuxt

### ISSUE THREAD

**Issue by gabe72** [lucaspulliese/vue-cool-lightbox#26]
Thanks for making this. 

This is the only one that has worked 80% with nuxt among all other libraries. However i am getting this issue.
![image](https://user-images.githubusercontent.com/42904245/79036599-61ff3b00-7be7-11ea-9d0a-fe95b76ea7c7.png)

**Comment by lucaspulliese** [comment]
Hi! Are you using the latest version? 
How are you using it?

**Comment by gabe72** [comment]
Hi Yes i am using the latest version. 

I have made a plugin lightbox js and added the code in there

**Comment by lucaspulliese** [comment]
Could you post a screenshot of how you're using it?

**Comment by gabe72** [comment]
Lighbox.js
![image](https://user-images.githubusercontent.com/42904245/79059930-58380f00-7c9d-11ea-8a18-2a6ee8a8f10a.png)

nuxt.config.js
![image](https://user-images.githubusercontent.com/42904245/79059940-6423d100-7c9d-11ea-8ecd-4c98fb47ef0f.png)

in the vue file
![image](https://user-images.githubusercontent.com/42904245/79059948-6d14a280-7c9d-11ea-8027-52a80370d3b0.png)

**Comment by gabe72** [comment]
![image](https://user-images.githubusercontent.com/42904245/79059978-9cc3aa80-7c9d-11ea-948a-dfaf28993cf8.png)

![image](https://user-images.githubusercontent.com/42904245/79059984-a816d600-7c9d-11ea-82eb-ea3a8e4c8c47.png)

**Comment by lucaspulliese** [comment]
Sorry for the late reply. 

Thanks for the screenshots, I will be working on it.

**Comment by lucaspulliese** [comment]
Hi @gabe72!

I did the same as your screenshots and I still can't reproduce the error, but I don't think it's a lightbox's problem, check this [stackoverflow link](https://stackoverflow.com/questions/49585845/attrs-is-readonly-listeners-is-readonly-avoid-mutating-a-prop-directly).

**Comment by lucaspulliese** [comment]
Closed since no response.
