### ISSUE TITLE
Feature: Add an option to swap the next and previous button action

### ISSUE THREAD

**Issue by jd1378** [lucaspulliese/vue-cool-lightbox#28]
Hi
I think it's good for UX if I can swap the direction that next and previous button goes in lightbox if possible in RTL templates, can you implement it if you don't mind ? like a `dir` option with `ltr` or `rtl` would be good to have

like for example I have 3 thumb images from right to left, clicking on the first from right opens the lightbox with index 0, now it should show the next button on the left of the light box that goes to index 1, but right now its on the right

this is what I want to achieve:
![Untitled](https://user-images.githubusercontent.com/6196533/79679821-69919600-821e-11ea-8ff6-df688387cc07.png)

**Comment by lucaspulliese** [comment]
Sure, I will add it in the new release. Thanks for the idea.

**Comment by lucaspulliese** [comment]
Hi! I know it's been a long time, I apologize, but I think now you can use it in the new version

Now in version 2.5.0 you can use it when a wrapper has direction: rtl, you can set a new prop dir="'rtl'" and it will work fine.

If everything is ok please close the issue.

**Comment by jd1378** [comment]
Hi
Thanks a lot for doing it! but I'm sorry I'm afraid I cannot test it any time soon
I close the issue for now as it seems to be done, I'll reopen it if I run into an issue.

**Comment by jd1378** [comment]
Hi again, I tried it out, It does swap the button location, but something strange happens,
Only the first image is visible
when it goes to the right , the next one is not coming into view from left
I'm not sure but I suspect the next slide is out on the right side

**Comment by jd1378** [comment]
It's fine, With applying dir="rtl" there should be a "direction: rtl" through css as well for it to work. 
It didn't work for me at first because I have a lot of stuff on ltr direction on the page.
It works fine now, thank you.
