### ISSUE TITLE
opening the gallery causes underlying page to scroll to the top

### ISSUE THREAD

**Issue by petermanlwl** [lucaspulliese/vue-cool-lightbox#3]
Ideally, when I click on an image/video, the underlying page should not scroll to the top. When I click out of the image/video, I expect the underlying page to look exactly the same as before I clicked the image. Instead, the underlying page is scrolled to the top.

**Comment by lucaspulliese** [comment]
Hi @petermanlwl! Could you give me your code?

**Comment by petermanlwl** [comment]
Hi,

Thanks for the fast response. I’ll send some repro steps soon.

--Peter

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by petermanlwl** [comment]
Hi,

I managed to reproduce the issue – see https://codesandbox.io/s/exciting-germain-bhwht
The issue disappears when line 106 of App.vue is commented out. Note that I’ve used other gallery vue-components, and they do not exhibit this bug.

Also, I noticed another issue.... if I do comment out line 106 (thereby ‘fixing’ the issue), I see that the scroll bar in the underlying page is hidden when I click on a gallery item. However, this causes a weird effect which causes all the contents to shift horizontally as I click in and out of the gallery item. Looks a bit weird – again, other Vue gallery components do not exhibit this issue.

Anyway, great work on vue-cool-lightbox – it’s really nice! I’ve chosen this component because it gives me what I want, and seems pretty bug free.

Keep up the good work!

--Peter

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
From: Peter Man <petermanlwl@live.co.uk>
Sent: Sunday, January 5, 2020 9:41:28 PM
To: lucaspulliese/vue-cool-lightbox <reply@reply.github.com>
Subject: RE: [lucaspulliese/vue-cool-lightbox] opening the gallery causes underlying page to scroll to the top (#3)


Hi,



Thanks for the fast response. I’ll send some repro steps soon.



--Peter



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10



________________________________

**Comment by petermanlwl** [comment]
Also, another possible issue I found, although I cannot reproduce in the example I sent you...

If I click on a youtube video so that it starts playing, then click away from the video to dismiss it, I get a “ERR_FILE_NOT_FOUND” error on the console.
In the stacktrace of that error, it points to vue-cool-lightbox.ems.js on line 437. It looks like this.itemSrc evaluates as false.

Thanks,

--Peter

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
From: Peter Man <petermanlwl@live.co.uk>
Sent: Sunday, January 5, 2020 9:52:04 PM
To: lucaspulliese/vue-cool-lightbox <reply@reply.github.com>
Subject: RE: [lucaspulliese/vue-cool-lightbox] opening the gallery causes underlying page to scroll to the top (#3)


Hi,



I managed to reproduce the issue – see https://codesandbox.io/s/exciting-germain-bhwht

The issue disappears when line 106 of App.vue is commented out. Note that I’ve used other gallery vue-components, and they do not exhibit this bug.



Also, I noticed another issue.... if I do comment out line 106 (thereby ‘fixing’ the issue), I see that the scroll bar in the underlying page is hidden when I click on a gallery item. However, this causes a weird effect which causes all the contents to shift horizontally as I click in and out of the gallery item. Looks a bit weird – again, other Vue gallery components do not exhibit this issue.



Anyway, great work on vue-cool-lightbox – it’s really nice! I’ve chosen this component because it gives me what I want, and seems pretty bug free.



Keep up the good work!



--Peter



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10



________________________________
From: Peter Man <petermanlwl@live.co.uk>
Sent: Sunday, January 5, 2020 9:41:28 PM
To: lucaspulliese/vue-cool-lightbox <reply@reply.github.com>
Subject: RE: [lucaspulliese/vue-cool-lightbox] opening the gallery causes underlying page to scroll to the top (#3)


Hi,



Thanks for the fast response. I’ll send some repro steps soon.



--Peter



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10



________________________________

**Comment by lucaspulliese** [comment]
Thanks for your feedback!

Ok, I will be working on those issues this week, currently I'm very busy but I'm gonna try to fix those issues tomorrow.

**Comment by lucaspulliese** [comment]
Fixed in release [0.1.2](https://github.com/lucaspulliese/vue-cool-lightbox/releases/tag/0.1.2)

Here's your forked codesandbox with the latest release updated https://codesandbox.io/s/runtime-fire-wp2zr

Please close the issue if everything is okay.

**Comment by petermanlwl** [comment]
That fixed the scrolling issue. Thanks!
