### ISSUE TITLE
Selectable text and html content

### ISSUE THREAD

**Issue by filipinyo** [lucaspulliese/vue-cool-lightbox#30]
Hey there!

I really like the lightbox. One thing that I'm missing is an option to pass in description a HTML. I'd like to add some URL in the description etc. Other thing that would need tweaking is the selectability of the text in the description and caption.

Best regards,

Filip

**Comment by lucaspulliese** [comment]
Hi Filip!

Now you can add HTML in description and title too if you want, and the text is selectable too in version 2.2.0.

**Comment by filipinyo** [comment]
Awesome! Thank you very much :D
