### ISSUE TITLE
Support other Video Formats

### ISSUE THREAD

**Issue by Buffalom** [lucaspulliese/vue-cool-lightbox#31]
Is it correct that only mp4-videos are recognized and displayed as videos? If so, would love to see other formats such as .mov being supported. Thanks!

**Comment by lucaspulliese** [comment]
Hi @Buffalom!

Yes, you are right, I will add other formats such as .mov and .ogg.

**Comment by lucaspulliese** [comment]
Hey @Buffalom, now in version [2.2.2](https://www.npmjs.com/package/vue-cool-lightbox) you can use .mov, .ogg, .webm and .avi as a videos types.

If everything is ok please close the issue. And thanks for this enhancement.

**Comment by Buffalom** [comment]
Ah right, sorry, I forgot to try again and close the issue. I have not tried it since to be honest but I'm sure it works 👍
