### ISSUE TITLE
Support "No Cookie" mode

### ISSUE THREAD

**Issue by migo315** [lucaspulliese/vue-cool-lightbox#33]
YouTube offers an API for embed videos with less cookies:

`https://www.youtube-nocookie.com/embed/YOUTUBE_ID`

Unfortunately, this does not work for this lightbox. In terms of data protection, this would be very relevant for European countries. Any chance to support this?

**Comment by lucaspulliese** [comment]
Hi @migo315!

First of all, thanks for the star.

Sure, I will add it, I didn't know that exists.

But I have a question. What do you thinks is better, just add to all youtube videos the embed video with less cookies or add a prop to decide between the one that add more cookies or the one that add less?

Currently what the lightbox do is get the youtube ID from the inserted url and use it in `https://www.youtube.com/embed/YOUTUBE_ID`

**Comment by migo315** [comment]
> First of all, thanks for the star.
It's a cool Lightbox library. ;-)

> Currently what the lightbox do is get the youtube ID from the inserted url and use it in 
Ok, but why don't you use the url directly? Generally, I would prefer if the library use the URL which I pass to items. But if that not possible, then a prop would be cool. The developer should decide which Embed variant should be use in his project.

**Comment by lucaspulliese** [comment]
> Ok, but why don't you use the url directly?

I don't use the url directly because is an iframe and only works with embed youtube videos. 
I have clients where they store the video url like this `https://www.youtube.com/watch?v=YOUTUBE_ID` and in that way doesn't work. 

But now thinking on it I could solve it checking if the URL is a youtube video and has 'embed' I will use it directly, if not there you decide wich embed variant should be use with a prop.

What do you think?

**Comment by migo315** [comment]
> I have clients where they store the video url like this https://www.youtube.com/watch?v=YOUTUBE_ID and in that way doesn't work.

Ah yes. That make sense. Well, then I think the prop is enough. It doesn't have to be more complicated than necessary.

**Comment by lucaspulliese** [comment]
Hi @migo315.

Now in version [2.3.0](https://www.npmjs.com/package/vue-cool-lightbox) you can use a prop called youtubeCookies, by default is true, if you set the prop to false it will work with `https://www.youtube-nocookie.com/embed/YOUTUBE_ID`

**Comment by migo315** [comment]
Cool! I will test it tonight. ;-)

**Comment by migo315** [comment]
Works perfectly! Click [here](https://coaster.cloud/parks/phantasialand/attractions/taron) if you want to see it action.

Thanks for that ;-)

**Comment by lucaspulliese** [comment]
You are welcome! 

And thanks, I always want to see sites that are using this component, it makes me feel good haha. 
By the way, good site, I like the design :)
