### ISSUE TITLE
Add autoplay prop for videos

### ISSUE THREAD

**Issue by LorenzoSapora** [lucaspulliese/vue-cool-lightbox#34]
Reading through your docs, and I can't see any autoplay prop for <video> content.

Unless it's hidden somewhere, I'll start making a PR for this feature :)

**Comment by lucaspulliese** [comment]
Hi @LorenzoSapora!

If you want to make the pull request it's ok for me!

But If not I will try to have today or tomorrow this feature.

**Comment by santas156** [comment]
it will be nice

**Comment by narindersahani** [comment]
Please send option name for auto play videos when popup opens
Thanks

**Comment by lucaspulliese** [comment]
Hi guys! 

I know it's been a long time, I apologize, but I think now you can use it in the new version.

For example:

```javascript
items: [
  {
    src: 'https://www.youtube.com/watch?v=2cZ_EFAmj08',
    autoplay: true,
  }
]
```

It works with youtube, vimeo and web videos :)

If everything is ok please close the issue.

**Comment by lucaspulliese** [comment]
Closed since no response. Feel free to open again if anything occurs.

**Comment by narindersahani** [comment]
Hi,
Sorry I missed your comment,
Thank for your support. I will check auto play and let you know if all good :)

Thanks a lot !

**Comment by narindersahani** [comment]
Auto play video working fine. Thanks a lot!

`items: [
  {
    src: 'https://www.youtube.com/watch?v=2cZ_EFAmj08',
    autoplay: true,
  }
]`
