### ISSUE TITLE
Clicking background doesn't close lightbox on mobile

### ISSUE THREAD

**Issue by kaypro4** [lucaspulliese/vue-cool-lightbox#35]
Hello, first thing, this is a fantastic tool so thank you so much for the time and effort that has been put into it. It is simple to integrate, and works beautifully. 

I'm not sure if this is an issue or a feature request, but on desktop (chrome) when I click outside of the image (see image below for click location)  when the lightbox is open, the lightbox closes. This is what I expect and prefer. 

When I do the same thing on a mobile device (tested on android and ios) the lightbox doesn't close, and in fact the lightbox controls at top right go away. I would prefer that a click the the overlay area always close the ligthbox. 

Is this intentional behavior or is it something that can be fixed or added?

Thanks again!

![image](https://user-images.githubusercontent.com/6536955/82842881-18656980-9e90-11ea-9f10-399d111c1253.png)

**Comment by lucaspulliese** [comment]
Hello @kaypro4!

Thank you very much for your words, I am very happy that the component is very helpfull to the community.

Yep, this is an intentional behavior, seriously I don't know now why haha, I was thinking that they could watch the videos or the gallery without the buttons disturbing, but yes, I think it's better what you said, or maybe add a prop for that. 

I will be working on it, thanks you again!

**Comment by kaypro4** [comment]
Thanks @lucaspulliese ! I like the idea of a prop since it would allow folks to keep things the way they are if they prefer. 

If my skills were better, I would dive into it myself. That said, if I can be of use as a tester please let me know.

**Comment by lucaspulliese** [comment]
Sure! I'll let you know 👍

**Comment by lucaspulliese** [comment]
Hey! 

Now in version [2.3.2](https://www.npmjs.com/package/vue-cool-lightbox) you have a prop called closeOnClickOutsideMobile, if is setted to true the lightbox will close on mobile devices when you click outside the image/video.

Test it please, if it works fine please close the issue :)

**Comment by kaypro4** [comment]
@lucaspulliese it's working perfectly for me! Thanks for getting this feature in so quickly!
