### ISSUE TITLE
Error on close with fade effect

### ISSUE THREAD

**Issue by ionchi** [lucaspulliese/vue-cool-lightbox#36]
Hello, I'm getting this error with 2.3.1 version every time I'm trying to close the slideshow (clicking outside the image or on close button):
```
client.js?06a0:84 TypeError: url.match is not a function
    at VueComponent.getYoutubeID (vue-cool-lightbox.esm.js?5547:1059)
    at VueComponent.getYoutubeUrl (vue-cool-lightbox.esm.js?5547:1072)
    at VueComponent.getVideoUrl (vue-cool-lightbox.esm.js?5547:1035)
```

the problem seems to be the fade effect, with swipe it works.

**Comment by lucaspulliese** [comment]
Hi @ionchi.

Thanks, I will fix it today 👍

**Comment by lucaspulliese** [comment]
Hey, could you reproduce the error in a codepen or post screenshot of how you are using it? I can't reproduce the error locally.

**Comment by ionchi** [comment]
Hi, thanks for the work. I can't reproduce that, it's part of a larger project. I tried with codesandbox but there it works, maybe the problem is elsewhere, I'll dig another bit later. 

Anyway, I'm fine with using swipe effect, but with that I'm also experiencing an issue:
with mixed gallery of images and videos, navigating the gallery doesn't load the video. It only works if opened directly with the relative index.

This is the reproduction sandbox:
[https://codesandbox.io/s/nuxt-playground-1e73q
](url)

Let me know if I have to open another issue for that.

**Comment by lucaspulliese** [comment]
Hey! Update the package to 2.3.3, It will work right now :)

**Comment by ionchi** [comment]
yes, now it works! Cool
