### ISSUE TITLE
Mouse Wheel control

### ISSUE THREAD

**Issue by krokodilshnap** [lucaspulliese/vue-cool-lightbox#37]
Hi! I'm really enjoy your plugin, thx for your work. But can you pls add mouse wheel control? It will be very comfortable

**Comment by krokodilshnap** [comment]
this part of code can be helpful for you. I realize mouse wheel event on your component 

```
wheelEvent(event) {
      const delay = 350;
      const currentTime = new Date().getTime();
      let direction = event.deltaY > 0 ? 'top' : 'down';

      if (currentTime - this.prevTime < delay) return;

      this.prevTime = currentTime;

      switch (direction) {
        case 'top':
          if (this.index <= 0) {
            this.index = 0;
            return false;
          }
          this.index--;
          break;
        case 'down':
          if (this.index >= (this.items.length - 1)) {
            this.index = this.items.length - 1;
            return false;
          }
          this.index++;
      }


    }
```

where `this.prevTime` is `new Date().getTime()`

**Comment by lucaspulliese** [comment]
Hi @krokodilshnap!

Great, I will test it, and if it works fine I'm going to add it. 

Thank you very much for your help!

**Comment by lucaspulliese** [comment]
Hey! 

I tested it and it works fine! Just did small changes, but now in version [2.3.2](https://www.npmjs.com/package/vue-cool-lightbox) you have enableWheelEvent prop, if everything is ok for you please close the issue. 

I will update the docs soon and give you the recognition for helping me with this improvement ;)

**Comment by krokodilshnap** [comment]
Thank you very much :))
