### ISSUE TITLE
Nuxt error

### ISSUE THREAD

**Issue by fayazara** [lucaspulliese/vue-cool-lightbox#38]
So I am trying to implement this with Nuxt, and I keep getting this error. `Cannot read property 'clientWidth' of undefined` when I was trying #19.

I am loading this in the component rather than loading it globally from the plugins folder.

Please let me know how to fix this.

**Comment by lucaspulliese** [comment]
Hi @fayazara!

Could you post screenshots of how you are implementing it?

**Comment by krokodilshnap** [comment]
Hi @fayazara 
I implemented this plugin in nuxt and its work fine. Be sure you made everything correct:

1. create a single file in plugins folder like "lightboxGallery"
2. past this code there 
```
import Vue from 'vue';
import CoolLightBox from 'vue-cool-lightbox';
import 'vue-cool-lightbox/dist/vue-cool-lightbox.min.css';

Vue.use(CoolLightBox);
```
3. In your `nuxt.config.js` file add a new object in `plugins` array 
`{ src: '@/plugins/lightboxGallery', mode: 'client' }`
4. In your component call `CoolLightBox` component

I'm using nuxt 2.0.0
