### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by indexxd** [lucaspulliese/vue-cool-lightbox#39]
Hi, I have a problem with performance depending on how many images I have. If I'm using 50 images everything is fast and smooth but when I change it to something more such as 500, the lightbox becomes very slow and takes around 2 seconds to open or change image. 

I don't really know what to do with this. Another lightbox I was using before didn't have this issue.

**Comment by lucaspulliese** [comment]
Hi @indexxd!

Have you tested it with fade effect? Because if with the fade effect works fine I will know what it's happening.

I don't know what kind of site are you doing, but show 500 images I think it's too much for the user, and It will take a lot to download that size of images.

**Comment by indexxd** [comment]
Yes, fade effect fixed this issue for me, thanks.
