### ISSUE TITLE
Multiple slideshows

### ISSUE THREAD

**Issue by nncrns** [lucaspulliese/vue-cool-lightbox#40]
First of all, thanks for this super useful tool!

I am trying to implement several slideshows for each section on a page as the result of a for-loop:

```
<template>
  <section v-for="app in page.apps" :key="app.id">
    <CoolLightBox 
      :items="items" 
      :index="index"
      loop
      @close="index = null">
    </CoolLightBox>

    <div class="images-wrapper">
      <div
        class="image"
        v-for="(image, imageIndex) in items"
        :key="imageIndex"
        @click="setIndex(imageIndex)"
        :style="{ backgroundImage: 'url(' + image.src + ')' }"
      ></div>
    </div>
  </section>
</template>
```

However, this gets me stuck in an endless loop. As I am still a Vue beginner, I am a little lost on how to make multiple slideshows possible. Maybe you could point me in the right direction?

Thanks!

**Comment by lucaspulliese** [comment]
Hi @nncrns!

I did this and it worked for me

```javascript
created() {
   this.apps.forEach((currentValue, index) => {
     this.$set(this.apps[index], 'index', null)
   });
},
```

```javascript
<section v-for="app in apps" :key="app.id">
  <CoolLightBox 
    :items="app.items" 
    :index="app.index"
    loop
    @close="app.index = null">
  </CoolLightBox>

  <div class="images-wrapper">
    <div
      class="image"
      v-for="(image, imageIndex) in app.items"
      :key="imageIndex"
      @click="app.index = imageIndex"
      :style="{ backgroundImage: 'url(' + image.src + ')' }"
    ></div>
  </div>
</section>
```

What I did was create a reactive variable for each of the items 'apps' using $set: [vue documentation](https://es.vuejs.org/v2/guide/reactivity.html#Precauciones-detectando-cambios)

Tell me if it works for you, and close the issue please.

**Comment by nncrns** [comment]
Thank you for the super fast reply and this solution, works perfectly! 🙏
