### ISSUE TITLE
srcMediaType not working on SignedUrl

### ISSUE THREAD

**Issue by elalekey** [lucaspulliese/vue-cool-lightbox#46]
Hey, @lucaspulliese , it's me again, xD.  If I use a signed Amazon URL with Cloudfront like this...

http://xyz.cloudfront.net/xyz.pdf?Expires=1591994230&Policy=eyJTDXYZBLABLABLABLABLALONGBLABLALIKE5109CHARS&Key-Pair-Id=APKAXYZAMXYZ

and I pass it by property "iframe" or "pdf" this keeps rendering it to me as an image. I tried to use the srcMediaType but nothing, it doesn't work

**Comment by lucaspulliese** [comment]
Hi again! haha

Try this:

```javascript
items: [
  {
    src: 'http://xyz.cloudfront.net/xyz.pdf?Expires=1591994230&Policy=eyJTDXYZBLABLABLABLABLALONGBLABLALIKE5109CHARS&Key-Pair-Id=APKAXYZAMXYZ',
    mediaType: 'iframe'
  }
]
```

I have to update the docs with an example like this one.

**Comment by elalekey** [comment]
I just tried it, it didn't work :(

If you want to give me a private email to send you a test URL so you can try it.
