### ISSUE TITLE
Scroll Lock

### ISSUE THREAD

**Issue by Shade465** [lucaspulliese/vue-cool-lightbox#47]
Hi! Please add scroll lock like a BodyScrollLock.

**Comment by betz0r** [comment]
You can realize that using the following snippet, this.index is pointing to the index used

` watch: {
            scrollDisable: function() {
                if(this.scrollDisable){
                    document.documentElement.style.overflow = 'hidden'
                    return
                }
                document.documentElement.style.overflow = 'auto'
            }
        },`

and 
`computed: {
            scrollDisable: function () {
                return this.index != null
            }
}`

**Comment by dmumedical** [comment]
> You can realize that using the following snippet, this.index is pointing to the index used
> 
> ```
> watch: {
>             scrollDisable: function() {
>                 if(this.scrollDisable){
>                     document.documentElement.style.overflow = 'hidden'
>                     return
>                 }
>                 document.documentElement.style.overflow = 'auto'
>             }
>         },
> ```
> 
> and
> 
> ```
> computed: {
>             scrollDisable: function () {
>                 return this.index != null
>             }
> }
> ```

See what the library does. The best solution is to remove content jumps when the scroll is blocked.

**Comment by Shade465** [comment]
> You can realize that using the following snippet, this.index is pointing to the index used
> 
> ```
> watch: {
>             scrollDisable: function() {
>                 if(this.scrollDisable){
>                     document.documentElement.style.overflow = 'hidden'
>                     return
>                 }
>                 document.documentElement.style.overflow = 'auto'
>             }
>         },
> ```
> 
> and
> 
> ```
> computed: {
>             scrollDisable: function () {
>                 return this.index != null
>             }
> }
> ```

See what the library does. The best solution is to remove content jumps when the scroll is blocked.

**Comment by lucaspulliese** [comment]
Yep, I realized that this does not work, I am trying to make this component not dependent on other libraries, but if I do not find a solution I will include BodyScrollLock. 

Sorry @Shade465, I was very busy and I was not very aware of the component, I will try to catch up with updates.

**Comment by lucaspulliese** [comment]
@Shade465 I updated the lightbox to a new version, 2.4.3, wich includes this fix. The only thing is I couldn't test it on iOS devices. 

Please tell me if everything works fine.

**Comment by lucaspulliese** [comment]
Closed since no response, feel free to open the issue again if you want.

**Comment by Shade465** [comment]
Thx) All ok, and sorry for the late reply
