### ISSUE TITLE
video url's don't work with google storage --fix in comments

### ISSUE THREAD

**Issue by BetKingIO** [lucaspulliese/vue-cool-lightbox#48]
Google storage and other cloud providers will add an access key on to the url after the file extension.
These url's don't work in cool lightbox.

If you modify the checkIsMp4 and getVideoExt to check if the url contains a video extension instead of checking if it ends then it works.

I didn't submit a pull request in case that breaks any other functionality but these changes work in my project.

**Comment by lucaspulliese** [comment]
Hi @BetKingIO!

Yes, you are right, I will be working on it.

**Comment by lucaspulliese** [comment]
Hi @BetKingIO! 

Sorry, I know it's been a while, but in the latest version, 2.4.2, this issue is fixed. 

If you can, please close the issue if everything is ok.

**Comment by BetKingIO** [comment]
Thanks for the update.
