### ISSUE TITLE
TypeError: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by matt127127** [lucaspulliese/vue-cool-lightbox#5]
Get this error when clicking on any image.

This is the line that is throwing the error:
 var ytId = (url.match(youtubeRegex)) ? RegExp.$1 : false;

**Comment by lucaspulliese** [comment]
Hi @matt127127, sorry for the late reply, I will check this issue right now, but if you can make a JSfiddle and reproduce the issue it will be better and faster for me to resolve it

**Comment by mairofte** [comment]
Hello @matt127127 
I had the same error message when I wanted to use a custom key for my image list.  I managed to "fixed" it by using the **index** from **v-for** loop as key and index prop for the CoolLightBox.
It seems that **CoolLightBox**  search the **items** list  only by index.

Hope this helps. Good luck

**Comment by lucaspulliese** [comment]
Thanks @mairofte, I will try to fix it today.
