### ISSUE TITLE
RTL issue

### ISSUE THREAD

**Issue by deasurv** [lucaspulliese/vue-cool-lightbox#53]
Hi.
First of all, thanks for your useful and beautiful tool!

I realized lightbox doesn't work good in RTL pages or every wrapper that has "dir: rtl" property. it only shows first image.

Hope you fix this soon :)

**Comment by lucaspulliese** [comment]
Hi @deasurv!

Thanks! I'm glad that you liked.

Sure, I will try to reproduce this fix and I will fix it 👍

**Comment by lucaspulliese** [comment]
Hi again! 

Now in version 2.5.0 you can use it when a wrapper has direction: rtl, you can set a new prop dir="'rtl'" and it will work fine.

If everything is ok please close the issue.

**Comment by deasurv** [comment]
Hey!

"dir" prop solved the problem! Thanks!

Keep it up!
