### ISSUE TITLE
Image resource protected by Bearer auth.

### ISSUE THREAD

**Issue by uwejan** [lucaspulliese/vue-cool-lightbox#54]
I was wondering if there was a way to load an image that is protected by auth headers. auth type Bearer token.

**Comment by lucaspulliese** [comment]
Hi @uwejan!

For images, the best approach for solve something like this I think is using signed URL as [this post](https://stackoverflow.com/questions/34096744/how-should-i-load-images-if-i-use-token-based-authentication) says.

**Comment by lucaspulliese** [comment]
@uwejan sorry, I couldn't find another solution, I will close this issue.
