### ISSUE TITLE
Compensate for scrollbar

### ISSUE THREAD

**Issue by vedmant** [lucaspulliese/vue-cool-lightbox#56]
Original fancybox compensates scrollbar jump https://prnt.sc/ue57cw

**Comment by lucaspulliese** [comment]
Yep, I did something like that before but in some browsers it didn't work, so I think I should add something like [bodyScrollLock](https://github.com/willmcpo/body-scroll-lock). 

But thanks for the suggestion!

**Comment by lucaspulliese** [comment]
Hi @vedmant! I added bodyScrollLock in version 2.6.0, tell me if it work fine for you.

**Comment by vedmant** [comment]
@lucaspulliese Thanks!

**Comment by vedmant** [comment]
@lucaspulliese Just checked, not exactly what I mean, it's compensate-for-scrollbar class, that compensates window just when body scroll is locked, it adds right padding to body (when there is a scrollbar). Here is some old package about this https://github.com/srph/scrollbar-compensate

**Comment by lucaspulliese** [comment]
Ahh sorry, my bad, I will check that package, thanks.

**Comment by lucaspulliese** [comment]
Hi @vedmant, you can update the component to version 2.6.1, I added the same as Fancybox do, let me know if it works fine for you.

**Comment by markhayok** [comment]
Hi, @lucaspulliese! First of all – great work!
I have a problem when I try to close the "lightbox" on the mobile device:

TypeError: document.getElementById(...) is null
(removeCompensateForScrollbar vue-cool-lightbox.esm.js:484)

"nuxt": "^2.14.6",
"vue-cool-lightbox": "^2.6.1"

**Comment by lucaspulliese** [comment]
Hi @markhayok! Thank you so much!

Update the component to version 2.6.2, It will fix it. 

Let me know if that works for you.

**Comment by markhayok** [comment]
@lucaspulliese  Thank you very much! Work well now!
