### ISSUE TITLE
Background changes on page scroll

### ISSUE THREAD

**Issue by kimanihuon** [lucaspulliese/vue-cool-lightbox#59]
Hi, great work.

I'm having a problem when displaying the lightbox when the page has scrolled down from the original position of the component. I'm programmatically opening the lightbox from different parts of the page, and passing in different images.

The problem is that half the background is cut off.

"nuxt": "^2.14.5",
"vue-cool-lightbox": "^2.5.2",
"@nuxtjs/vuetify": "^1.11.2",

To reproduce:
https://pastebin.pl/view/221c71ca

**Comment by lucaspulliese** [comment]
Hello! Thanks!

Oh I see, I think I should add something like [bodyScrollLock](https://github.com/willmcpo/body-scroll-lock), wich I thinks is more tested than the solution than I did. 

Thanks @kimanihuon, I will let you know when is fixed.

**Comment by lucaspulliese** [comment]
Hi again @kimanihuon! I added bodyScrollLock in version 2.6.0, tell me if everything works fine for you.

**Comment by kimanihuon** [comment]
Hi, awesome. The scrolling issue has been fixed. Thank you very much.

**Comment by kimanihuon** [comment]
One last thing, with the new update, the image doesn't update when I change the src programmatically. e.g

`activeImages[0].src = newUrl`

I'm thinking maybe it's a caching thing ... kindly advise.

**Comment by lucaspulliese** [comment]
Let me check it out and I'll tell you what it might be

**Comment by schellmax** [comment]
might be related, using the CDN version i get the following error in the console:

vue-cool-lightbox:1 Uncaught ReferenceError: bodyScrollLock is not defined

**Comment by lucaspulliese** [comment]
@schellmax Hi! 

Yep, you are right, I forgot to remove that text and add that dependency to the docs for the CDN case, thanks!

**Comment by lucaspulliese** [comment]
Done @schellmax. Thanks again.
