### ISSUE TITLE
Multiple Galleries in one page

### ISSUE THREAD

**Issue by diogoareia** [lucaspulliese/vue-cool-lightbox#60]
Can't get multiple galleries to work on the same page, the first one works smoothly after that the others don't change the images, only the first one shows correctly.

**Comment by diogoareia** [comment]
> Can't get multiple galleries to work on the same page, the first one works smoothly after that the others don't change the images, only the first one shows correctly.

Got it to work with effect = "fade", swipe not working

**Comment by diogoareia** [comment]
Just checked your examples, and this also happens on the ones with effect="swipe" after the first example.
I'm using Google Chrome lateste version Version 85.0.4183.121 (Official Build) (64-bit) on Mac OS Catalina

**Comment by lucaspulliese** [comment]
Hi @diogoareia!

You are right, I will try to figure out this weekend, I don't know what's happening, thank you very much for reporting the problem.

**Comment by lucaspulliese** [comment]
@diogoareia Please update the component to version 2.6.3, as you can see in the docs, it's fixed in that version. But let me know if it works for you aswell.

**Comment by croftman** [comment]
@lucaspulliese I can confirm it's now working well 👍

**Comment by diogoareia** [comment]
It's perfect, thank you so much!!!! 
Cheers

**Comment by thaminayasmin** [comment]
Code sample for multiple galleries please. How do I work with the index. Weird.
