### ISSUE TITLE
Video is still playing in background after clicking Next or Previous

### ISSUE THREAD

**Issue by StormWitcher** [lucaspulliese/vue-cool-lightbox#61]
**How to reproduce**
1. Go to the official example https://vue-cool-lightbox.lucaspulliese.com/#example-video
2. Open the first video
3. Click Play
4. Click to next video

Now you can still hear the previous video is still playing in the background and if you click play in the current video, it will play overlapping the previous one. A free remix :) 

**Expected result**
When clicking the Next or Previous button, the current playing video will stop and move on to the other video in the item list.

**Comment by lucaspulliese** [comment]
Hi @StormWitcher!

First of all, thanks for the star :).

Yup, you are right, I will check that issue today, thanks!

**Comment by StormWitcher** [comment]
Thank you for the quick fix. Highly appreciate.
I confirmed the issue is solved in the latest version 2.6.6.

**Comment by lucaspulliese** [comment]
You're welcome!

I didn't tell you about to test the component because I saw a small bug on Vimeo videos, but it's not something that breaks the component funcionality, but I will let you know when it's fixed.

**Comment by lucaspulliese** [comment]
Hi again @StormWitcher.

I fixed that issue on Vimeo videos on version 2.6.7. Thanks for the enhancement.

Cheers!

**Comment by StormWitcher** [comment]
Well done!

Thanks for the fixes and I love the component.
