### ISSUE TITLE
No alt attribute on <img>

### ISSUE THREAD

**Issue by Dezento** [lucaspulliese/vue-cool-lightbox#62]
Hey, this plugin is really cool, but it lacks alt attribute on img  tag,
it would be also cool if it could have a dynamic alt tag (because of the new ADA regulations)

**Comment by lucaspulliese** [comment]
Hi @Dezento!

Thanks for the star :).

Yup, it's a good enhancement, I will let you know when I have it, thanks!

**Comment by lucaspulliese** [comment]
Update the component to version 2.6.7, as you can see in the docs, now you can pass the attribute alt to the item object.

**Comment by Dezento** [comment]
@lucaspulliese Thanks for the enhancement! :)
