### ISSUE TITLE
Body scroll error

### ISSUE THREAD

**Issue by zachu90** [lucaspulliese/vue-cool-lightbox#63]
Hi,
This package is awesome. Thank you for creating it.
I only have one issue with it. It keeps throwing error in the console:

`bodyScrollLock.esm.js?e181:192 enableBodyScroll unsuccessful - targetElement must be provided when calling enableBodyScroll on IOS devices.`

I am using chrome on windows 10.

Any ideas on how to fix this?

**Comment by lucaspulliese** [comment]
Hi @zachu90!

Thanks for your words! :D

What version are you using? Because I fixed that before. 
Another question, if you go to the docs, does it throw you the error as well?

**Comment by zachu90** [comment]
@lucaspulliese I am using `"vue-cool-lightbox": "^2.6.7"`

If I go to the docs the error isn't there.

I am using the package with Nuxt SPA mode. 
The errors are thrown when I navigate from one page to another. 

The stacktrace shows that the method is invoked by vue-cool-lightbox:

```
  beforeDestroy: function beforeDestroy () {
    if (this.enableScrollLock) {
      this.removeCompensateForScrollbar();
      enableBodyScroll(this.$refs.coolLightbox);
    }
  },
```

**Comment by changefox** [comment]
Great package Lucas. I really like it!

I'm am also getting the same thing. Using `"vue-cool-lightbox": "^2.6.7",` like zuchu90
For my case, the error triggers when I navigate away from the page with VCL. You can see what happens for me here:
![MyReflections-JSError](https://user-images.githubusercontent.com/26835266/97996679-07e3f280-1e23-11eb-9b43-b75eec060309.gif)

My implementation of VCL is pretty basic;

`
        <div class="row justify-content-center m-0 p-0">

            <div class="col-12 text-center ml-0 pl-0 mr-0 pr-4">

                <CoolLightBox 
                    :items="attachment.images" 
                    :index="index"
                    :effect="'fade'"
                    @close="index = null">
                </CoolLightBox>

                <div class="card-columns">
                    <div class="card" v-for="(image, imageIndex) in attachment.images" :key="imageIndex">
                        <img 
                            class="pointer"
                            :src="image.src"                                
                            @click="index = imageIndex"
                        /> 
                    </div>
                </div>

            </div>

        </div>
`
I also using Chrome on W10

Hope that helps you get to the bottom of it :) Thanks!

**Comment by lucaspulliese** [comment]
Thanks to both for the info! I will take a look today 👍

**Comment by lucaspulliese** [comment]
Hello guys! 

Sorry for taking so long to solve it, I've had a lot of work this week. Please update the component to 2.6.8 version and let me know if everything work fine for you.

**Comment by zachu90** [comment]
@lucaspulliese Thanks a lot! Version 2.6.8 fixes the issue for me,

**Comment by changefox** [comment]
Yeah good for me too! :)
