### ISSUE TITLE
Base64 data for image src 

### ISSUE THREAD

**Issue by thehovdev** [lucaspulliese/vue-cool-lightbox#64]
is this possible in this package ?

i use this code but it does not work

> <CoolLightBox
>               :items="photos"
>               :index="index"
>               srcName="image"
>               srcMediaType="data:image/jpeg;base64"
>               @close="index = null">
>             </CoolLightBox>

**Comment by changefox** [comment]
I believe the srcMediaType is used for to switch between images/video and iframes but I could be wrong

**Comment by lucaspulliese** [comment]
Hi @thehovdev!

Yep, but it's not going to work in that way, It's what @changefox said, that prop is for src items, and it's, for example, when you have an url which is an PDF but it's not possible to detect the extension.

Check this [example](https://jsfiddle.net/lucaspulliese/xrado08c/), you just need to add the base64 image to the src item.
