### ISSUE TITLE
I can't use vue-cool-lightbox pls help me out

### ISSUE THREAD

**Issue by ntt19981812** [lucaspulliese/vue-cool-lightbox#66]
my component:

`<template>
  <div>
    <CoolLightBox :items="items" :index="index" @close="index = null">
    </CoolLightBox>
    <div class="images-wrapper">
      <div
        class="image"
        v-for="(image, imageIndex) in items"
        :key="imageIndex"
        @click="index = imageIndex"
        :style="{ backgroundImage: 'url(' + image.src + ')' }"
      ></div>
    </div>
  </div>
</template>
<script>
import CoolLightBox from "vue-cool-lightbox";
import 'vue-cool-lightbox/dist/vue-cool-lightbox.min.css'
export default {
  name: "HelloWorld",
  components: {
    CoolLightBox,
  },
  data() {
    return {
      items: [
        {
          title: "Image 1",
          description: "Description 1",
          src:
            "https://images.unsplash.com/photo-1607339531106-864a9bda946a?crop=entropy&cs=srgb&fm=jpg&ixid=MXwxNDU4OXwwfDF8cmFuZG9tfHx8fHx8fHw&ixlib=rb-1.2.1&q=85",
        },
        {
          title: "a beautiful mountain view",
          description: "Description 2",
          src:
            "https://images.unsplash.com/photo-1605559222535-22e9009cbc0c?crop=entropy&cs=srgb&fm=jpg&ixid=MXwxNDU4OXwwfDF8cmFuZG9tfHx8fHx8fHw&ixlib=rb-1.2.1&q=85",
        },
        {
          title: "Youtube Video",
          description: "Youtube Video",
          thumb: "thumb.jpg",
          src: "https://www.youtube.com/watch?v=d0tU18Ybcvk",
        },
      ],
      index: null,
    };
  },
};
</script>

<style scoped>
</style>
`

**Comment by lucaspulliese** [comment]
Hello @ntt19981812! 

Can you send me the error that are you getting? And how are you implementing the component please?

**Comment by ntt19981812** [comment]
i fixed it

**Comment by solamichealolawale** [comment]
I have the same problem, can't get it work.
https://codesandbox.io/s/vue-cool-lightbox-sample-lgl4m
