### ISSUE TITLE
Can't resolve Vue Cool Lightbox

### ISSUE THREAD

**Issue by solamichealolawale** [lucaspulliese/vue-cool-lightbox#69]
I installed the package and attached is the error mesage I encountered.

![image](https://user-images.githubusercontent.com/12444227/103092376-4f9f2300-45f7-11eb-8421-8a9d8f488849.png)

I even tried using Code Sandbox 
https://codesandbox.io/s/vue-cool-lightbox-sample-lgl4m

It's not working. Perhaps, I am doing something wrong.

Then I noticed there's nothing except for package.json in the node_module folder for vue-cool-lighbox
![image](https://user-images.githubusercontent.com/12444227/103092527-d0f6b580-45f7-11eb-9a93-17c46c5de816.png)

**Comment by lucaspulliese** [comment]
Hi @solamichealolawale! 

I don't know what's happening there, try again to install the component running `npm i vue-cool-lightbox`.

Don't forget to add the css (`import 'vue-cool-lightbox/dist/vue-cool-lightbox.min.css'`), and the styles to the div where the images are shown.

```
.images-wrapper {
  display: flex;
}

.images-wrapper .image {
  width: 300px;
  height: 300px;
  background-size: cover;
}
```

Check this [example](https://jsfiddle.net/lucaspulliese/x5dqvm9k/).

Hope this help.

**Comment by solamichealolawale** [comment]
The example given is using CDN. What I am using is the npm version of it. I think that's where the problem comes from
