### ISSUE TITLE
loop work only for fade effect

### ISSUE THREAD

**Issue by MavlinD** [lucaspulliese/vue-cool-lightbox#70]
loop work only for fade effect, for swipe don`t(

**Comment by lucaspulliese** [comment]
Hello @MavlinD!

Yep, it's something that I should add in a future new version.

**Comment by chrisbjr** [comment]
Maybe the documentation should change as it states here that it only works with "swipe"

![image](https://user-images.githubusercontent.com/571279/124745218-2a01b780-df52-11eb-89cd-77676707fcfb.png)
