### ISSUE TITLE
Specify button type - default "submit" causes issue inside form

### ISSUE THREAD

**Issue by mike-13** [lucaspulliese/vue-cool-lightbox#9]
Would it be possible to set the type of all buttons to "button" inside the template? The default button type is "submit" and when the lightbox is used inside a form, it causes the form to be submitted.

**Comment by lucaspulliese** [comment]
Sure! You're right, I will do it now. My bad and sorry.

**Comment by alexelev** [comment]
I join the request - I have the same problem with the lightbox's buttons inside the form and there is no way to change the type of buttons or even replace them with a `div` for example. The provided slots do not give such an opportunity, only change the content inside the buttons.

**Comment by lucaspulliese** [comment]
Fixed in release [1.0.12](https://github.com/lucaspulliese/vue-cool-lightbox/releases/tag/1.0.12)

**Comment by mike-13** [comment]
Thanks, you're doing a great job in developing this lightbox

**Comment by lucaspulliese** [comment]
Thank you so much! Glad to hear that :D
